---
- set_fact:
    iam_exec_role: "{{ iam_exec_arn }}"
    function_name: s3-message-processor

- name: AWS Lambda Function
  lambda:
    region: eu-central-1
    name: "{{ function_name }}"
    description: lambda function to take unicorn rental messages and send them to the scoring API
    zip_file: "{{ s3_deployment_package }}"
    runtime: python2.7
    timeout: 20
    handler: "{{ s3_filename }}.handle"
    memory_size: 1024
    role: "{{ iam_exec_role }}"
  register: lambda_results

- name: "alias 'dev' for function {{ function_name }}"
  lambda_alias:
    region: eu-central-1
    function_name: "{{ function_name }}"
    name: dev
    description: Development is always the $LATEST version
